### ISSUE TITLE
`exclude` property in tsconfig.json is not pointing to the correct path

### ISSUE THREAD

**Issue by mhegazy** [dbiele/TypeScript-Cordova-SystemJS-Angular2-beta#4]
From a cursory look, I do not not think the `exclude` property in [tsconfig.json](https://github.com/dbiele/TypeScript-Cordova-SystemJS-Angular2-beta/blob/master/CODE/scripts/tsconfig.json#L15) is pointing to the correct location. if i were to guess, i would say folder: https://github.com/dbiele/TypeScript-Cordova-SystemJS-Angular2-beta/tree/master/CODE/scripts/tests was the one meant to be excluded. if this is the case, then the value should be `"tests"` instead of `"../www/scripts/tests/"`. also looks like the `rootDir` is using an unnecessary long form to mean `"."`.

**Comment by mhegazy** [comment]
in general all file path in a tsconfig.json file are relative to the the tsconfig.json file location. see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/tsconfig.json.md for more details.

**Comment by DeanB2015** [comment]
@mhegazy Thanks for the help!.  The `tests` value was the solution.    

```
"exclude": [
    "tests"
  ]
```
