### ISSUE TITLE
Question about the cordova.js

### ISSUE THREAD

**Issue by sunshineo** [dbiele/TypeScript-Cordova-SystemJS-Angular2-beta#5]
In your index.html

<script src="cordova.js"></script>

I'm also serving the www folder to the web for browsers, and after added this, it gives me 404 all the time (of course it does).
How to dynamically include this file based on platform?
Or if possible, I would prefer to add this when I do cordova build. Is this possible?

Thank you very much!

**Comment by DeanB2015** [comment]
@sunshineo I just saw you message. I'll be able to look into this later today, but wanted to ask a few questions to clarify:
- What browser are you using to test?
- Do you have a repo with the forked version and your code updates?
- Are you using the VS2015 > Task Runner Explorer > Tasks > browser.sync to start a web server and view?  If not, please let me know how you're viewing in the browser.
- I'm not sure what you mean when you say platform?  Do you mean browsers, operating systems or mobile devices?

Thanks, Dean

**Comment by sunshineo** [comment]
I'm looking for something like this. This uses jquery mobile to detect and decide if include cordova.js or not
https://gist.github.com/dhavaln/2886774
But I don't like that it uses jquery mobile

**Comment by DeanB2015** [comment]
@sunshineo Thanks for the link and the clarification.  I believe a modification to `\scripts\index.ts` will provide the solution to your feature request.

```
/**
 * Waits for Cordova or if not on a device and cordova is not needed, don't wait and call onDeviceReady.
 */
function initializeCordova(): void {
    if (!window.cordova) {
//Add your web browser code here.
        onDeviceReady();
    } else {
        document.addEventListener('deviceready', onDeviceReady, false);
    }
}
```

the `if (!window.cordova) {` detects if window.cordova exists.  window.cordova only exists when on a mobile device.  Adding code in this if statement will run in a web browser.

Does this answer your questions? I hope this helps.

Thanks

Dean

**Comment by sunshineo** [comment]
What about the script tag
`<script src="cordova.js"></script>`
?

Should I place cordova.js also for my web, so it does not create a 404?

**Comment by DeanB2015** [comment]
@sunshineo
The 404 are appearing for the `cordova.js` and  `scripts/platformOverrides.js`.  Both of the files are generated when building the project as a mobile app in VS2015.  However, if the code is run in a browser, the files don't exist.  
![404-errors](https://cloud.githubusercontent.com/assets/10567383/13657683/0fec46f6-e63f-11e5-9806-3530cd1fb255.PNG)

I just updated the repo to include placeholder `cordova.js` and  `scripts/platformOverrides.js` files. The files only contains comments to clarify their purpose. I think this solves the 404 problem?  

Let me know what you think.

Dean

**Comment by sunshineo** [comment]
I think it's a good idea!
